import "@App/modules/mono/services/Auth"
import "@App/modules/mono/AuthUI"
import "@App/modules/mono/menu"
import "@App/modules/mono/statementUI"
import "@App/modules/mono/currencyUI"
import "@App/modules/mono/partners"
import "@App/modules/main/settings"
import "@App/modules/main/flags"
