import "./Polyfills"
import "./AutoErrorReport"
import "./FatalErrorListener"
import "./CoreLoaderListener"
import "./LanguageSettings"
import "./ThemeSettings"
import "./SetPreloader"
import "./SetSplashscreen"
